/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://docs.edgeimpulse.com/page/terms-of-service) or Enterprise Terms of
 * Service (https://docs.edgeimpulse.com/page/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes[] = { 0, 13, 26 };

// (before - mean) / scale
const float ei_classifier_anom_scale[3] = { 1.8712869679502173, 0.6792056368112124, 2.039090690148221 };
const float ei_classifier_anom_mean[3] = { 1.9565971138743246, 0.8458315862070133, 2.705451140582289 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters[32] = {
	{ ( float[3] ) { -1.0392024517059326, -1.2276488542556763, -1.3178367614746094 }, 0.03163406379653756 },
	{ ( float[3] ) { 1.1873022317886353, -0.133052796125412, 0.9008083343505859 }, 0.3904932249938027 },
	{ ( float[3] ) { -0.4878925681114197, 0.6748805642127991, 0.10252179205417633 }, 0.4055470493727547 },
	{ ( float[3] ) { 1.0845743417739868, 0.22511066496372223, 0.9507235884666443 }, 0.29636576614790316 },
	{ ( float[3] ) { 1.1782279014587402, 0.6177423596382141, 0.31387338042259216 }, 0.7110203477268774 },
	{ ( float[3] ) { -0.30837592482566833, 0.8272266387939453, 0.32748332619667053 }, 0.3382691845007247 },
	{ ( float[3] ) { -0.3361172378063202, 1.273672342300415, 0.5353386998176575 }, 0.30517399901596615 },
	{ ( float[3] ) { -0.09682977199554443, 1.1383702754974365, 0.3249075412750244 }, 0.39907953446481265 },
	{ ( float[3] ) { 0.9088584184646606, 0.14166761934757233, 0.48687925934791565 }, 0.29339134129777183 },
	{ ( float[3] ) { 0.5270885229110718, 0.02910507656633854, 0.3204720616340637 }, 0.3842094508052329 },
	{ ( float[3] ) { 0.7193398475646973, -0.19783639907836914, 0.8567496538162231 }, 0.452044158737377 },
	{ ( float[3] ) { 1.3065917491912842, 0.9489337801933289, 0.976561963558197 }, 0.3889835614594584 },
	{ ( float[3] ) { 1.3936293125152588, -0.480103075504303, 1.0878269672393799 }, 0.3916907147008569 },
	{ ( float[3] ) { -0.4635131061077118, 0.9868823885917664, 0.10507714748382568 }, 0.34305993386093026 },
	{ ( float[3] ) { -0.48089221119880676, -0.009365793317556381, -0.3170599937438965 }, 0.5966300922383884 },
	{ ( float[3] ) { 1.5319503545761108, 0.39475002884864807, 1.6255191564559937 }, 0.3401513898755018 },
	{ ( float[3] ) { -0.23386745154857635, 0.1733560562133789, 0.4184531271457672 }, 0.3437494867448209 },
	{ ( float[3] ) { -0.3167251646518707, 0.47236010432243347, 0.08950537443161011 }, 0.2780127550401349 },
	{ ( float[3] ) { 1.9307228326797485, 0.0799504816532135, 1.3572440147399902 }, 0.2087544988881544 },
	{ ( float[3] ) { 1.2883708477020264, 0.5237187147140503, 0.9063354134559631 }, 0.3653211825319026 },
	{ ( float[3] ) { 1.6178969144821167, 0.7684946060180664, 0.9710358381271362 }, 0.3799979875097753 },
	{ ( float[3] ) { 1.3864108324050903, 0.11558206379413605, 1.0563963651657104 }, 0.26131664037512053 },
	{ ( float[3] ) { 1.1060234308242798, -0.04585908353328705, 0.591547966003418 }, 0.24185650443523127 },
	{ ( float[3] ) { -0.16250330209732056, 0.8883643746376038, 0.6372647881507874 }, 0.39950883911029206 },
	{ ( float[3] ) { 0.11386850476264954, 1.2354103326797485, 0.005584815517067909 }, 0.3556383991965599 },
	{ ( float[3] ) { 0.11384496092796326, 1.2447874546051025, 1.0227795839309692 }, 0.3998393483422998 },
	{ ( float[3] ) { 1.4973105192184448, -0.18063856661319733, 1.1997222900390625 }, 0.32668933573396 },
	{ ( float[3] ) { -0.2537270188331604, 1.5698422193527222, 0.8065485954284668 }, 0.30943680192183337 },
	{ ( float[3] ) { 1.9725019931793213, 0.49977394938468933, 1.141434669494629 }, 0.4198284017180318 },
	{ ( float[3] ) { -0.291929692029953, 1.650465726852417, 0.33168989419937134 }, 0.48075573025483775 },
	{ ( float[3] ) { 1.6287392377853394, 0.8474501371383667, 1.4793026447296143 }, 0.36496914899864774 },
	{ ( float[3] ) { -0.1334618330001831, 3.4194724559783936, 0.6104882955551147 }, 0.2722931346836712 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
